version: '3.9'

services:
  turbo:
    container_name: turbo
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
      - "1337:1337"
    environment:
      - STRAPI_VERSION=4.0.2
    env_file:
      - ./apps/strapi/.env.prod
    volumes:
      - ./:/app/
      - ./node_modules:/app/node_modules/
    restart: on-failure
    depends_on:
      - mysql
    networks:
      - private
      - public

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    env_file:
      - ./apps/strapi/.env.prod
    networks:
      - private

volumes:
  mysql:
    name: strapi-db

networks:
  private:
  public:
