FROM node:18-slim

RUN npm install pm2@latest --global

ENV NODE_ENV production

WORKDIR /app

COPY package*.json .

COPY . .

RUN npm install turbo --global

RUN npm ci --only=production

RUN npm install --arch=arm64 --platform=linuxmusl sharp

RUN mkdir node_modules/.cache && chmod -R 775 node_modules/.cache

RUN npm run build

EXPOSE 3000 1337

CMD ["npm", "run", "start"]

