version: '3.9'

services:
  turbo:
    container_name: turbo
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "1337:1337"
    environment:
      - STRAPI_VERSION=4.0.2
    env_file:
      - ./apps/strapi/.env
    volumes:
      - ./:/app/
      - ./node_modules:/app/node_modules/
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - private
      - public

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 7432:5432
    env_file:
      - ./apps/strapi/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - private

volumes:
  postgres:
    name: strapi-db

networks:
  private:
  public:
