---
name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}

      - name: Rsync to Remote Server
        run: |
          rsync -rtvpl  --delete-after \
          -e 'ssh -o StrictHostKeyChecking=no' \
          $GITHUB_WORKSPACE/ \
          ${{ secrets.REMOTE_USERNAME }}@${{ vars.REMOTE_HOST }}:${{ vars.REMOTE_PATH }}

      - name: SSH into Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ vars.REMOTE_PATH }} && docker-compose -f docker-compose.prod.yml down
            cd ${{ vars.REMOTE_PATH }} && docker-compose -f docker-compose.prod.yml up -d
